### ISSUE TITLE
latency和responseTime的单位需要在文档明确一下为us

### ISSUE THREAD

**Issue by Minnull** [vesoft-inc/k6-plugin#30]
latency, time consuming in nebula server.
responseTime, time consuming in client.
两个指标为封装k6后的自定义指标，需要明确在文档明确一下为us单位

**Comment by HarrisChu** [comment]
chanage `latency` to `latencyInUs`

**Comment by HarrisChu** [comment]
refer:https://github.com/vesoft-inc/k6-plugin/blob/master/example/nebula-test-insert.js

```
var latencyTrend = new Trend('latency', true);
var responseTrend = new Trend('responseTime', true);
```

and then the metrics could be time with unit
