### ISSUE TITLE
依赖的k6 v0.33.0版本太久

### ISSUE THREAD

**Issue by Minnull** [vesoft-inc/k6-plugin#31]
依赖的k6 v0.33.0版本太久，k6目前提供v0.39的版本，期望升级，方便支持：https://k6.io/docs/javascript-api/ ，的k6/execution api

**Comment by HarrisChu** [comment]
> 

预计 9 月初更新 k6 版本

**Comment by HarrisChu** [comment]
already update to v0.40.0
===

已经更新到 v0.40.0
