### ISSUE TITLE
After increasing concurrency, it is unable to return test results.

### ISSUE THREAD

**Issue by cooler810** [vesoft-inc/k6-plugin#40]
100并发可以正常返回，200就会有这个错误，看请求都是正常的，但是压测结果无法返回
`ERRO[0080] failed to handle the end-of-test summary error="GoError: failed to open connection, error: failed to verify client version: read tcp *****:22811->******:9669: i/o timeout \n\tat reflect.methodValueCall (native)\n\tat file:****/nebulagraph-bench/templates/k6_config.js.j2:12:27(59)\n"`

**Comment by HarrisChu** [comment]
graph 上有日志么？可以试一下 150 并发会不会有问题，然后看一下 graph 使用了多少的 cpu

**Comment by QingZ11** [comment]
@cooler810 hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
